apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /data/MQTT_CLIENT_ID
        value: "foxwatch-staging"
      - op: replace
        path: /data/RUST_LOG
        value: "debug"
    target:
      kind: ConfigMap
      name: foxwatch-config
